import Link from "next/link"
import { Button } from "@/components/ui/button"
import { MessageSquare, Users, Zap } from "lucide-react"

export default function WhatsAppChannels() {
  return (
    <div className="flex flex-col">
      {/* Hero Section */}
      <section className="relative isolate overflow-hidden bg-gradient-to-b from-purple-900/90 to-background pt-14 pb-20">
        <div className="absolute inset-0 -z-10 h-full w-full bg-[radial-gradient(circle_at_center,rgba(120,50,255,0.15),transparent_70%)]" />
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-3xl py-32 sm:py-48">
            <div className="text-center">
              <h1 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">WhatsApp Channels</h1>
              <p className="mt-6 text-lg leading-8 text-gray-300">
                Launch AI-powered WhatsApp channels for broadcasts and chatbots to engage with your audience.
              </p>
              <div className="mt-10 flex items-center justify-center gap-x-6">
                <Button
                  asChild
                  size="lg"
                  className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 transition-all duration-300 shadow-[0_0_15px_rgba(139,92,246,0.3)] hover:shadow-[0_0_20px_rgba(139,92,246,0.5)]"
                >
                  <Link href="https://automapi.com/login" target="_blank" rel="noopener noreferrer">
                    Get Early Access
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-background">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl lg:text-center">
            <h2 className="text-base font-semibold leading-7 text-purple-600">Features</h2>
            <p className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Engage Your Audience Where They Are</p>
            <p className="mt-6 text-lg leading-8 text-gray-400">
              Connect with your customers on WhatsApp, the most popular messaging platform in the region, with
              AI-powered capabilities.
            </p>
          </div>

          <div className="mx-auto mt-16 max-w-7xl">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
              <div className="relative flex flex-col overflow-hidden rounded-lg border bg-background p-8">
                <div className="flex h-16 w-16 items-center justify-center rounded-full bg-purple-600/10">
                  <MessageSquare className="h-8 w-8 text-purple-600" />
                </div>
                <h3 className="mt-6 text-xl font-semibold">AI Chatbots</h3>
                <p className="mt-2 flex-1 text-gray-400">
                  Create intelligent chatbots that can answer customer queries, provide support, and guide users through
                  processes.
                </p>
              </div>

              <div className="relative flex flex-col overflow-hidden rounded-lg border bg-background p-8">
                <div className="flex h-16 w-16 items-center justify-center rounded-full bg-purple-600/10">
                  <Users className="h-8 w-8 text-purple-600" />
                </div>
                <h3 className="mt-6 text-xl font-semibold">Broadcast Channels</h3>
                <p className="mt-2 flex-1 text-gray-400">
                  Send targeted messages to your audience segments with personalized content generated by AI.
                </p>
              </div>

              <div className="relative flex flex-col overflow-hidden rounded-lg border bg-background p-8">
                <div className="flex h-16 w-16 items-center justify-center rounded-full bg-purple-600/10">
                  <Zap className="h-8 w-8 text-purple-600" />
                </div>
                <h3 className="mt-6 text-xl font-semibold">Quick Integration</h3>
                <p className="mt-2 flex-1 text-gray-400">
                  Set up your WhatsApp business account and connect it to our platform in minutes with our guided setup
                  process.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 bg-gradient-to-b from-background to-purple-900/20">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Ready to engage your audience on WhatsApp?
            </h2>
            <p className="mt-6 text-lg leading-8 text-gray-300">
              Join businesses across Oman and the Gulf who are using Nuqta AI's WhatsApp Channels to connect with their
              customers.
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <Button
                asChild
                size="lg"
                className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 transition-all duration-300 shadow-[0_0_15px_rgba(139,92,246,0.3)] hover:shadow-[0_0_20px_rgba(139,92,246,0.5)]"
              >
                <Link href="https://automapi.com/login" target="_blank" rel="noopener noreferrer">
                  Get Early Access
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
